[project]
name = "textfilter"
version = "0.1.0"
description = ""
readme = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "tokenizers>=0.15.0",
]

[tool.setuptools]
py-modules = ["generate"]
packages = []
